version: "3.9"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    environment:
      FLASK_ENV: development
      REDIS_URL: redis
      REDIS_PORT: 6379
  redis:
    image: "redis:alpine"
