apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: web

---

apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redis
